### PR TITLE
[WIP] Refactors package to separate downloading capabilities from the rest [WIP]

### PR DESCRIPTION
**Pull request by pedrocamargo**
* Refactors to separate downloading capabilities from the rest
* import errors
* circumvents NetworkX lack of algorithm

### CODE REVIEW

**Comment by pedrocamargo** [comment]
@gboeing , This is my first stab on it (I took the opportunity to fix that error that was appearing in some other pull requests (test_stats), which you might need to evaluate better. I may have made the wrong fixing there).

In case you agree with where I am taking this, I will start the integration with AequilibraE and then we can see if this undertaking works as expected for everybody.

**Comment by kylebarron** [comment]
A refactor seems useful because `core.py` is so large. +1

**Comment by pedrocamargo** [comment]
@gboeing ?

**Comment by gboeing** [comment]
@pedrocamargo the CI tests were fixed in #350, can you undo your changes to the tests module that worked around it?

**Comment by gboeing** [comment]
Also: reading through the file changes, there's a lot to process in your proposed refactor. Could you succinctly document here in a comment what's changed and why? That'll help both for the review and for future reference.

**Comment by pedrocamargo** [comment]
Document it in code or in here?

**Comment by gboeing** [comment]
Here for now.

**Comment by pedrocamargo** [comment]
@gboeing , the test has been reversed

**Comment by pedrocamargo** [comment]
@gboeing 
As mentioned in the PR, the main objective of the PR is to separate the OSM downloading capabilities from the geo-processing and graph-processing algorithms
The list of changes include:

1. Separating all the custom errors into a file dedicated to them
2. Moving the routines from utils which are applicable to geo-processing  into geo_utils.py
3. Moving all routines for OSM downloading into downloader.py
4. Moving the OSM content handler into its own file (It makes sense having a well-defined class like that into its own file)

With these changes, anybody that wants to use OSMNx only to download OSM data and wrangle the data with different tools won't have to deal with more complicated dependencies, which is usually an issue on Windows.
This way OSMNX becomes a more attractive dependency for projects that don't require that copious amount of dependencies, AequilibraE being an example of such.

**Comment by gboeing** [comment]
@pedrocamargo this has been merged and will be released shortly in v0.11

**Comment by pedrocamargo** [comment]
Thanks, @gboeing !

**Pull request merged**
