### PR TITLE
Roundabouts bug in osm_xml

### PR DESCRIPTION
**Pull request by mxndrwgrdnr**
Related to #970. Handles NetworkX topology violation when converting ways to DAGs in osm_xml.py No new usage required.

### CODE REVIEW

**Comment by gboeing** [comment]
Looks like tests are failing.

**Comment by mxndrwgrdnr** [comment]
Sorry I was being lazy and using the github continuous integration to do my testing ;). Will test locally before my next push.

**Comment by gboeing** [comment]
@mxndrwgrdnr thanks. Would you add a line to the change log documenting this change?

**Comment by mxndrwgrdnr** [comment]
Done!

**Comment by mxndrwgrdnr** [comment]
Looks like the latest failures are just a 502 error from nominatim. I'll wait a bit and try to trigger the build again.

**Comment by gboeing** [comment]
> Looks like the latest failures are just a 502 error from nominatim. I'll wait a bit and try to trigger the build again.

No worries, I just re-ran them successfully. Thank you!

**Pull request merged**
