### PR TITLE
Catch key errors when deleting supporting geometry

### PR DESCRIPTION
**Pull request by AtelierLibre**
Delete instead of pop supporting polygons from the final dictionary of footprints. Catch key errors if items in the pop_list are not found in the footprints dictionary - this may be caused by duplicate items in pop_list attempting to delete items from the footprints dictionary multiple times.

### CODE REVIEW

**Comment by AtelierLibre** [comment]
@gboeing running it through as a set does seem to resolve the key error, however it may be best to wrap it up in a more complete fix. So happy to hold off on this for now if you think that's a better idea.

**Comment by gboeing** [comment]
@AtelierLibre sounds good

**Comment by AtelierLibre** [comment]
@gboeing I have a new version of `footprints.py` in a branch called `footprints_fix` in my repository. I think it succesfully resolves issues #270, #278, #279 however the change to the code is quite significant.

[https://github.com/AtelierLibre/osmnx/tree/footprints_fix](https://github.com/AtelierLibre/osmnx/tree/footprints_fix)

On my machine #279 runs out of memory, however a smaller area (which still generates 4 responses) does complete.

```
point = (-6.5652,39.1172)
dist =26000
gdf = ox.footprints_from_point(point=point, distance=dist)
```

I introduced a `responses` parameter into `create_footprints_gdf` to allow for pickling between `osm_footprints_download` and `create_footprints_gdf` as some of the `responses` generated are quite large (approx. 500MB).

It needs more testing before I submit a pull request however I wanted to get it out there incase anyone else is able to test it and provide feedback.

Nick

**Comment by gboeing** [comment]
superseded by #289

**Pull request closed without merging**
