### PR TITLE
Option for download of other infrastructures

### PR DESCRIPTION
**Pull request by DavidBreuer**
A new keyword parameter infrastructure='way["highway"]' was added to enable download and analysis of other infrastructures:

    infrastructure : string
        download infrastructure of given type (default is streets (ie, 'way["highway"]') but other 
        infrastructures may be selected like power grids (ie, 'way["power"~"line"]'))

A neutral filter network_type='none' was added so that other infrastructures are not removed due to missing "highway" tags.

Thanks and best,
David

### CODE REVIEW

**Comment by gboeing** [comment]
Hi @DavidBreuer, thanks much for this PR! Looks like the Travis CI tests are currently failing -- can you give it a look and see what can be done to get this commit to pass the tests?

**Comment by gboeing** [comment]
@DavidBreuer nevermind, this seems to be a GDAL problem: https://github.com/conda-forge/gdal-feedstock/issues/151#issuecomment-310257157

**Comment by DavidBreuer** [comment]
Hi Geoff, ok, thanks!



Am 22.06.2017 um 04:22 schrieb Geoff Boeing:

**Comment by ocefpaf** [comment]
@DavidBreuer PR #64 helps to understand the issue, but my guess is that it is already resolved. Can you try to restart the CIs here so we can check?

**Comment by gboeing** [comment]
@ocefpaf re-ran the CIs, all working now, thanks!

**Comment by ocefpaf** [comment]
Glad it is resolved. Deployment of new versions in conda-forge is always like

**Pull request merged**
