### PR TITLE
Modify buildings module to work with multipolygon buildings

### PR DESCRIPTION
**Pull request by AtelierLibre**
**Please note I am putting this forward as a suggestion for comment/review**
This is my first pull request. I have not tested it extensively but would appreciate a review / comments to let me know if I am on the right track with the code. If a pull request is not the right way to do this please let me know.

The current buildings.py converts
- polygons tagged as buildings
- polygons part of relations tagged as buildings
to buildings.

This leads to overlapping building footprints where each member of a multipolygon relationship is converted to a building in its own right.

The proposal keeps this behaviour but additionally
- creates multipolygon buildings from the polygons already generated
- deletes the buildings that were created from supporting geometry polygons (i.e. not tagged in their own right)

I haven't included the nodes for the multipolygon buildings as am I unclear how useful that would be.

### CODE REVIEW

**Comment by gboeing** [comment]
@AtelierLibre thanks! Could you add a commit to include a test for this new functionality in the `tests` folder? For example, using the use case in #223.

**Comment by AtelierLibre** [comment]
@gboeing sure yes, will have a look into this

**Comment by gboeing** [comment]
closes #223

**Comment by gboeing** [comment]
@AtelierLibre just checking back on the test. We should be able to merge this PR after that is committed.

**Comment by gboeing** [comment]
This has been released in v0.9

**Pull request merged**
