### PR TITLE
speed up graph_from_gdfs

### PR DESCRIPTION
**Pull request by Labulitiolle**
I have not added a unit test as `test_find_nearest` already test this function. 
Regarding the performances for a graph with 97087 nodes and 274361 edges on my 8GB RAM:
- previous `ox.graph_from_gdfs` ~ 32s.
- new `ox.graph_from_gdfs` ~ 9s.

@gboeing Please let me know what you think.

### CODE REVIEW

**Comment by gboeing** [comment]
@Labulitiolle the PR's name and your comment refer to the `graph_to_gdfs` function but it looks like the `graph_from_gdfs` function is the only thing you're changing?

**Comment by Labulitiolle** [comment]
@gboeing, My bad, indeed I have only changed the `ox.graph_from_gdfs`.
Note that the `ox.graph_to_gdfs` is running in ~8s thus it is not such a big bottleneck for large datasets. 

I will have a look at this `ox.graph_to_gdfs` today to see if it can be Improved.

**Comment by gboeing** [comment]
@Labulitiolle I merged, but then reverted the merge.

I realized that this PR is adding a bunch of null attribute values to the graph edges. OSM attribute data are sparse, so there are lots of nulls in the node/edge GeoDataFrames. But in the MultiDiGraph attribute data, if a node or edge doesn't have a certain attribute, it should just lack that key:value pair (rather than having key:null).

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)

G = ox.graph_from_place('Los Angeles, CA, USA', network_type='drive')
print(len(G))

nodes, edges = ox.graph_to_gdfs(G)
G2 = ox.graph_from_gdfs(nodes, edges, graph_attrs=G.graph)
```

Then look at an edge in G:
```python
list(G.edges(keys=True, data=True))[0]
```
```
(653688,
 21300195,
 0,
 {'osmid': 398770659,
  'lanes': '6',
  'name': 'National Boulevard',
  'highway': 'secondary',
  'oneway': False,
  'length': 88.678,
  'geometry': <shapely.geometry.linestring.LineString at 0x1fa6fcc7af0>})
```

Then look at an edge in G2:
```python
list(G2.edges(keys=True, data=True))[0]
```
```
(653688,
 21300195,
 0,
 {'osmid': 398770659,
  'lanes': '6',
  'name': 'National Boulevard',
  'highway': 'secondary',
  'oneway': False,
  'length': 88.678,
  'geometry': <shapely.geometry.linestring.LineString at 0x1fa6fcc7af0>,
  'tunnel': nan,
  'bridge': nan,
  'ref': nan,
  'maxspeed': nan,
  'width': nan,
  'service': nan,
  'access': nan,
  'junction': nan})
```

Adding a bunch of null attributes to the node/edge attribute data dicts creates memory (and serialization) inefficiencies, even if it speeds up the gdfs -> graph conversion. We need to make sure null attributes are filtered out, as they were originally.

**Comment by gboeing** [comment]
@Labulitiolle see an idea for a fix in this branch: https://github.com/gboeing/osmnx/blob/fix/osmnx/utils_graph.py#L104-L146

Worth doing some profiling to see its runtime.

**Comment by gboeing** [comment]
Runtimes I'm seeing look like:
  - `master` branch: 16.5
  - `fix` branch: 5.8 seconds
  - your branch: 4.1 seconds

So the fix branch isn't quite as fast as your proposal, but it's close and it avoids the inefficiency of null attributes in all the nodes/edges. Let me know what you think and if you have any other suggestions.

**Comment by Labulitiolle** [comment]
Sorry @gboeing , I should have mentioned that I removed the 'not adding nan attributes' property. In the memory/speed tradeoff I tried to maximize speed as I am using your functions on large, filtered geodataframes.

I think your solution on the `fix branch` seems perfectly suited for OSMnx: Keeping low memory usage (important on OSM data) and significantly improving speed 🚀

**Comment by gboeing** [comment]
Proposed solution in #578.

**Pull request merged**
