### PR TITLE
Add scheduled Overpass and Nominatim API tests

### PR DESCRIPTION
**Pull request by migurski**
Adds tests for OpenStreetMap APIs designed to run on a schedule under AWS Lambda.

- [x] Test simple request to Nominatim
- [x] Test [remaining sample calls](https://github.com/gboeing/osmnx/issues/107#issuecomment-345540929)

This is a stub and I’m looking for feedback on the approach. `osm_api_tests.py` is outside the normal project hierarchy, and gets deployed to Lambda as a standalone Python 3 script. It’s possible but slightly annoying to include 3rd party packages on Lambda, so I’m using only standard library functionality. If merged, the AWS deployment details will need to be updated.

Will close https://github.com/gboeing/osmnx/issues/107.

### CODE REVIEW

**Comment by mmd-osm** [comment]
If I‘m not mistaken those API requests currently won’t provide a User-Agent in the http header, which would be helpful in case of issues. Also a bit more error handling for Overpass might be needed (think rate limiting).

**Comment by migurski** [comment]
Good point, I'll add a User-Agent header.

**Comment by gboeing** [comment]
@migurski thanks -- looking good. Could you tell me a little more about where and how this runs?

**Comment by migurski** [comment]
Sure! In the bottom of the Travis config file you’ll notice a new `deploy` section. Travis (for `migurski/osmnx` only) is configured with an AWS key/secret for my account to update the named Lambda function with code from the configured Python file. I configured a Cloudfront scheduled task to run the function every 15 minutes, and then attached an alarm to the graph of failures.

If it fails more than a couple times in an hour, the alarm triggers an email to me. So far, there seem to be a few intermittent failures suggesting that I should raise the threshold somewhat. This will require some tuning over time, starting with too many alarms until the threshold feels right.

This setup is effectively free to run, so if you’re interested in using it we can just continue to use my AWS account and add an email to you. Alternatively, I can help you get it set up under your own AWS account.

**Comment by mmd-osm** [comment]
To add a bit of confusion to this topic, you're actually testing the old server (136.243.42.136) only. osmnx  uses `overpass-api.de` in a few places, which would resolve to one of the two available servers via round robin. 

```
> www.overpass-api.de
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	www.overpass-api.de      << old server only
Address: 136.243.42.136             

     
> overpass-api.de
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	overpass-api.de
Address: 136.243.42.136                << old server
Name:	overpass-api.de
Address: 178.63.48.217                 << new server
> 
```

BTW:  testing once per hour should be sufficient as a test interval imho. Servers are not changing that often. In some cases you're already hitting rate limiting, i.e. queries get delayed a bit, or you even get an HTTP 429 response.

**Comment by migurski** [comment]
Thanks @mmd-osm, I updated the PR to reflect your suggested Overpass domain. When running these tests, we can space them out more. It’s just convenient to have them run more frequently while developing.

**Comment by gboeing** [comment]
@migurski looking good. Ready to merge to master? Should Travis config be updated to use master branch?

**Comment by gboeing** [comment]
resolves #107

**Comment by migurski** [comment]
I think it’s ready! It might require some coordination to get the secret updated for the current `gboeing/osmnx` repo instead of the `migurski/osmnx` fork. I will update the branch name here, and then after you merged you may need to make a followup edit for the AWS details. I’ll share those with you offline.

**Comment by gboeing** [comment]
Thanks @migurski !

**Comment by gboeing** [comment]
@migurski yep looks like we need to edit AWS details: https://travis-ci.org/gboeing/osmnx/jobs/318247643#L1116

Let me know how you'd like to proceed.

**Pull request merged**
