### PR TITLE
Add graph from file

### PR DESCRIPTION
**Pull request by migurski**
Introduces new `graph_from_file()` function in osmnx.core. Parses OSM XML files and generates Overpass-like JSON data. This is a stub implementation, and I'm looking for feedback on these questions before I continue:

- Is there some deeper underlying object format I should use in preference to Overpass JSON, or does this XML-to-JSON flow seem good?
- Do OSM relations need to be supported?
- What optional parameters need to exist for `graph_from_file()`?

Addresses #93.

### CODE REVIEW

**Comment by gboeing** [comment]
1. I think xml to json works well. That will make hand-off to [create_graph](https://github.com/gboeing/osmnx/blob/master/osmnx/core.py#L1262) easy enough.

2. As of now, no. But that's a future enhancement that'd be nice to make library-wide. For now, just adding a stub or comment or something pointing out it's not there would be useful.

3. I think `simplify`, `retain_all`, `network_type`, and `name`. Each is easy to handle in like a line or 2 of code such as [here](). The `network_type` argument is needed by create_graph to create bidirectional edges as appropriate. Presumably, the purpose of this new `graph_from_file` function is to turn the all the way contents of the .osm file into a graph, so I assume the function will not filter edge types based on the `network_type` argument. But I'm open to suggestions.

**Comment by gboeing** [comment]
and, thanks much for digging into this!

**Comment by migurski** [comment]
I think this is done. I’ve added a test for reading data from files, and I believe the unit failure test is something to do with geocoding.

**Comment by gboeing** [comment]
Thanks @migurski! I'll take a look at this soon.

**Comment by sevamoo** [comment]
Thanks a lot for this new function. It works very well.

**Comment by awa5114** [comment]
Does the pbf need to contain any specific information or can it contain all default osm data? For instance I have tried to run the `graph_from_file` function on a pbf generated from GeoFabriks Europe extract. The subextract I am using is for a very small test area with poly as follows:

```
1
0
    5.07448295115847     52.01761020898715
    5.061074139766845     52.020260672951096
    5.05768817426537     52.04045565493337
    5.064169334843836     52.07093448682436
    5.076798284522554     52.07550514373811
    5.100512051914809     52.065312416966435
    5.095128489319279     52.03868762461073
    5.07448295115847     52.01761020898715
END
END
```

The osmconvert command I did on the GeoFabrik extract is as follows:

`osmconvert64 europe.osm.pbf -B=test.poly -o=test.osm`

With no additional filters. I then try to run 

```
import osmnx

G = osmnx.graph_from_file('test.osm')
```

But I get an error

>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\netwerkanalyse\lib\site-packages\osmnx\core.py", line 1911, in graph_from_file
>     retain_all=retain_all, name=name)
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\netwerkanalyse\lib\site-packages\osmnx\core.py", line 1368, in create_graph
>     G = add_edge_lengths(G)
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\netwerkanalyse\lib\site-packages\osmnx\core.py", line 1201, in add_edge_lengths
>     coords = np.array([[u, v, k, G.nodes[u]['y'], G.nodes[u]['x'], G.nodes[v]['y'], G.nodes[v]['x']] for u, v, k in G.edges(keys=True)])
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\netwerkanalyse\lib\site-packages\osmnx\core.py", line 1201, in <listcomp>
>     coords = np.array([[u, v, k, G.nodes[u]['y'], G.nodes[u]['x'], G.nodes[v]['y'], G.nodes[v]['x']] for u, v, k in G.edges(keys=True)])
> KeyError: 'y'


Is it perhaps looping through some nodes/ways it does not actually need? Do I have to do more than simply extract all OSM data for a given extent? Do I have to filter for specific features before I use the `graph_from_file` function? If so it would be nice to include this in the docstring for this function....

**Comment by celhannah** [comment]
Has this function been removed?

**Comment by gboeing** [comment]
Yes, a year or two ago in the package reorganization. See the docs: https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.graph.graph_from_xml

**Pull request merged**
