### PR TITLE
Union filters

### PR DESCRIPTION
**Pull request by arkty**
# Union filters

Discussion: https://github.com/gboeing/osmnx/issues/1199

## Problem
When developing city graph models, the size of the resulting graph might be important. Thanks to OSMnx, it's possible to use a pre-defined filters to request  a network, based on desired types of OSM ways. But sometimes, it's needed to add an additional ways from OSM into network or union them based on multiple filters.

## Technical details
When using `custom_filter`, it's not possible to request additional roads by Overpass union condition.

## Example
We need to request additional road by name (The Road), ignoring all other conditions.

In Overpass this request will look like this:
```
(way[...](poly:'***'); way[name="The Road"](poly:'***'););
```

OSMnx constructs Overpass request like this, where `$filter` is pre-defined filter or provided by user.
```
[out:json][timeout:180];
(way[$filter](poly:'***');>;);
out;
```

## Proposal
Make `custom_filter` accepts not only string, but a list of filters and then combine the result into single graph. 
Because OSMnx already supports sub-divided requests, it's easy to implement this without changing logic on actual graph creation (simplification, connectivity, etc). 

## Usage example
On example of city Petrozavodsk we will use `graph_from_place ` with `network_type = "drive"`. This will give us a graph on a perfect level of details. But for some reason, two additional roads are required to be in model.

The request below correctly adds these roads.

```
ptz_graph = ox.graph_from_place(
    'Petrozavodsk, Russia',
    custom_filter=[
        op._get_network_filter("drive"),
        f'[name="улица Достоевского"]',
        f'[name="улица Калевалы"]'
    ]
)
```

### CODE REVIEW

**Comment by EwoutH** [comment]
Would something like this be possible? How would that work API wise in with this PR?

```Python
custom_filter = '["highway"~"motorway|motorway_link"]'
construction_filter = '["construction"~"motorway|motorway_link"]'
full_filter = ???
```

**Comment by arkty** [comment]
@EwoutH for OR filter it will be
```
highway_filter = '["highway"~"motorway|motorway_link"]'
construction_filter = '["construction"~"motorway|motorway_link"]'

# Full OR filter
custom_filter = [highway_filter, construction_filter]
```

**Comment by EwoutH** [comment]
That’s a really clean syntax, love it!

**Comment by gboeing** [comment]
@arkty tests are failing. Run the pre-commit hooks locally then push again.

**Comment by arkty** [comment]
@gboeing i've added a commit with style fix, can you please run wf again.

**Comment by EwoutH** [comment]
Awesome! Looking forward to using this in the next pre-release!

**Pull request merged**
